<a href="https://colab.research.google.com/github/afirdousi/pytorch-basics/blob/main/001_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



1.Check NVIDIA GPU Details
2.Import fundamental packages
3.Check pytorch version
4.Creating differnt types of tensors




In [ ]:
#check which GPU you have (SMI = System Management Interface)
!nvidia-smi

Thu Aug 17 05:38:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello Pytorch World!")
print(torch.__version__)

Hello Pytorch World!
2.0.1+cu118


In [ ]:
#scalar

scalar = torch.tensor(7) ## https://pytorch.org/docs/stable/tensors.html
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() # Get tensor back as python int

7

In [ ]:
#vector

vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
vector[2]

tensor(3)

In [ ]:
#matrix = a 2 dimensional array of number
# its a general convention to name matrix and tensors in upper case in python/ML land
MATRIX = torch.tensor([[1,2,3],
                        [4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
MATRIX[0]

tensor([1, 2, 3])

In [ ]:
MATRIX[1]

tensor([4, 5, 6])

In [ ]:
#tensor = an n dimensional array of number

TENSOR = torch.tensor([[
                        [1,2,3],
                        [4,6,2],
                        [7,9,8],
                        [6,2,7]
                      ]])

# number of items in each row needs to be the same, try putting more or less numbers in any row


In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 3])

In [ ]:
## Random Tensors - Used by NN to start off the network

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.1589, 0.3860, 0.4419, 0.4584],
        [0.2287, 0.0290, 0.4487, 0.4066],
        [0.8708, 0.5091, 0.5514, 0.0192]])

In [ ]:
random_tensor = torch.rand(3,4,5)
random_tensor

tensor([[[0.6367, 0.7129, 0.9345, 0.7481, 0.5304],
         [0.6931, 0.1926, 0.0731, 0.5243, 0.9785],
         [0.4180, 0.3527, 0.6215, 0.1429, 0.4346],
         [0.6819, 0.8649, 0.8500, 0.7796, 0.7702]],

        [[0.8293, 0.1870, 0.6625, 0.3310, 0.3641],
         [0.8990, 0.9562, 0.6990, 0.9154, 0.8959],
         [0.3637, 0.1177, 0.9434, 0.6072, 0.3863],
         [0.5040, 0.5923, 0.4563, 0.8585, 0.1883]],

        [[0.3426, 0.8576, 0.1184, 0.4312, 0.5334],
         [0.1936, 0.4022, 0.3856, 0.2581, 0.0315],
         [0.8719, 0.3874, 0.6756, 0.4186, 0.4824],
         [0.6793, 0.9121, 0.3126, 0.5351, 0.1563]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([3, 4, 5])

In [ ]:
# Create a random tensor to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224,224 )) ## 3 channels R-G-B, height, width --- size= is optional
random_image_size_tensor

tensor([[[0.0337, 0.8273, 0.6478,  ..., 0.5730, 0.7418, 0.7872],
         [0.2208, 0.3841, 0.2141,  ..., 0.3444, 0.1434, 0.5279],
         [0.4468, 0.2784, 0.4904,  ..., 0.0210, 0.6651, 0.0649],
         ...,
         [0.7256, 0.2991, 0.7677,  ..., 0.7401, 0.6215, 0.1624],
         [0.4292, 0.4455, 0.2795,  ..., 0.7843, 0.2261, 0.8056],
         [0.5338, 0.0680, 0.2487,  ..., 0.9796, 0.0829, 0.7861]],

        [[0.0731, 0.0649, 0.5462,  ..., 0.3709, 0.4073, 0.5142],
         [0.0216, 0.1694, 0.3692,  ..., 0.3690, 0.4465, 0.6345],
         [0.3225, 0.4360, 0.9270,  ..., 0.4960, 0.8181, 0.1098],
         ...,
         [0.1036, 0.8214, 0.2430,  ..., 0.7153, 0.3584, 0.6004],
         [0.1467, 0.9172, 0.9915,  ..., 0.5335, 0.7372, 0.1764],
         [0.3347, 0.8863, 0.0202,  ..., 0.1814, 0.7031, 0.2651]],

        [[0.3735, 0.6991, 0.1431,  ..., 0.4213, 0.1768, 0.6345],
         [0.9412, 0.8212, 0.0797,  ..., 0.2204, 0.4100, 0.5112],
         [0.2799, 0.8115, 0.0596,  ..., 0.2948, 0.7067, 0.

In [ ]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
# tensor of zeros and ones (used for Masking)

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
## Range tensors

torch.arange(0,10) # (start, end , step)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
even_between_one_to_100 = torch.arange(2,101,2)
even_between_one_to_100

tensor([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
         30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
         58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,
         86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
even_between_one_to_100 = torch.arange(start = 2, end = 101, step = 2)
even_between_one_to_100

tensor([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,
         30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
         58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,
         86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
## Creating look alike tensors (aka tensor like)

even_between_one_to_100.shape

torch.Size([50])

In [ ]:
fifty_zeros = torch.zeros_like(even_between_one_to_100) ## or fifty_zeros = torch.zeros_like(input = even_between_one_to_100)
fifty_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [ ]:
## Tensor Data types

float_32_tensor = torch.tensor([3.0,6.0], dtype=None) ## even thought we put none, default data type is going to be float32
float_32_tensor.dtype



torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0,6.0], dtype=torch.float16)
float_16_tensor.dtype


torch.float16

In [ ]:
test_tensor = torch.tensor([3.0,6.0], dtype=None, device=None, requires_grad=False)


In [ ]:
# 3 big errors you will run into:
# 1. Tensor is not right datatype
# 2. Tensor is not right shape
# 3. Tensor is not right device

In [ ]:
test_tensor = torch.tensor([3.0,6.0], dtype=None, device="cuda", requires_grad=False)
test_tensor


tensor([3., 6.], device='cuda:0')

In [ ]:
### convert data types
test_tensor = float_32_tensor.type(torch.float16) ### original variable remains as is
test_tensor

tensor([3., 6.], dtype=torch.float16)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor * float_32_tensor ## sometimes this can give error and then you will have to use conversion/casting

tensor([ 9., 36.])

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
# find details about tensor

# 1. datatype (.dtype)
# 2. shape (or the size() function)
# 3. device (.device)

In [ ]:
random_tensor = torch.rand(3,4)

In [ ]:
print(random_tensor)
print(f"Datatype of tensor:  {random_tensor.dtype}")
print(f"Shape of tensor:  {random_tensor.shape}")
print(f"Size of tensor:  {random_tensor.size()}")
print(f"Device of tensor:  {random_tensor.device}")

tensor([[0.7993, 0.1761, 0.5519, 0.0662],
        [0.8823, 0.9089, 0.4655, 0.9872],
        [0.6433, 0.2322, 0.1731, 0.8473]])
Datatype of tensor:  torch.float32
Shape of tensor:  torch.Size([3, 4])
Size of tensor:  torch.Size([3, 4])
Device of tensor:  cpu
