<a href="https://colab.research.google.com/github/afirdousi/pytorch-basics/blob/main/002_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello Pytorch World!")
print(torch.__version__)

Hello Pytorch World!
2.0.1+cu118


In [3]:
### Manipulating Tensors (addition, subtraction, element-wise multiplication, division, matrix multiplication)

# Create a tensor

tensor = torch.tensor([10, 20, 30])
tensor + 100

tensor([110, 120, 130])

In [8]:
tensor - 10

tensor([ 0, 10, 20])

In [4]:
tensor * 100

tensor([1000, 2000, 3000])

In [5]:
tensor / 10

tensor([1., 2., 3.])

In [7]:
tensor # original tensor hasn't changed

tensor([10, 20, 30])

In [10]:
tensor.mul(10) # same as tensor * 10 --- prefer to use basic python operations

tensor([100, 200, 300])

In [12]:
torch.add(tensor, 500)

tensor([510, 520, 530])

In [17]:
#matrix multiplication

#Two ways of multiplication in Neural nets
# 1/ element wise multiplication can be multiply matrix by a scalar or multiplying two tensors element wise
# 2/ matrix multiplication meaning multiplying two matrices aka dot product

#1
print(tensor * tensor) # element wise multiplication

#2
torch.matmul(tensor, tensor) # matrix multiplication = 10*10 + 20*20 + 30*30 = 100 + 400 + 900

tensor([100, 400, 900])


tensor(1400)

In [18]:
# check which operator is faster (matmul) or doing matrix multiplication with raw python operators
%%time
value = 0
for i in range(len(tensor)):
  value = value + tensor[i]
print(value)

tensor(60)
CPU times: user 2.73 ms, sys: 0 ns, total: 2.73 ms
Wall time: 2.8 ms


In [20]:
%%time
torch.matmul(tensor, tensor) # even with a tensor of 3 elements matmul is 6x faster, imagine the effect on tensor of 1000 elements

CPU times: user 490 µs, sys: 0 ns, total: 490 µs
Wall time: 399 µs


tensor(1400)

In [22]:
%%time
tensor @ tensor ## @ is short form for matmul --- runs a little slower than matmul I believe (Check)
# another option is tensor.mm() its a direct alias of .matmul()

CPU times: user 762 µs, sys: 0 ns, total: 762 µs
Wall time: 703 µs


tensor(1400)

In [25]:
# common errors: shape error
# for dot product, col of first matrix should match with row of second matrix

# Run the following and it will fail (this is the common shape error)
#torch.matmul( torch.rand(3,2) , torch.rand(4,2)) # RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 4x2)

In [26]:
# following will work
torch.matmul( torch.rand(3,2) , torch.rand(2,4)) # the results will have # of rows of first and # of columns of second (3,4)

tensor([[0.2735, 0.3862, 0.4608, 0.2032],
        [0.5140, 0.8307, 0.8298, 0.3767],
        [0.0531, 0.1572, 0.0612, 0.0355]])

In [28]:
# what if we have two tensors that cannot be multipled?
# how can we update the tensors to make it work? take transpose!

tensor_one = torch.rand(3,4)
tensor_two = torch.rand(3,4)

print(tensor_one)
print(tensor_two)

tensor([[0.0447, 0.5213, 0.2183, 0.8195],
        [0.8184, 0.5144, 0.4304, 0.8499],
        [0.1568, 0.2409, 0.2897, 0.3780]])
tensor([[0.4058, 0.3444, 0.2587, 0.8655],
        [0.1147, 0.3405, 0.2211, 0.1258],
        [0.2567, 0.8136, 0.5463, 0.2811]])


In [31]:
# Action: run this, it would fail due to # of col of first not matchin # of col of second
# tensor_one.mm(tensor_two) ## RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [32]:
tensor_two.T # this will change shape from 3,4 to 4,3 --- this can now be multiplied by tensor_one

tensor([[0.4058, 0.1147, 0.2567],
        [0.3444, 0.3405, 0.8136],
        [0.2587, 0.2211, 0.5463],
        [0.8655, 0.1258, 0.2811]])

In [37]:
torch.matmul(tensor_one, tensor_two.T)

tensor([[0.9634, 0.3340, 0.7852],
        [1.3563, 0.4711, 1.1027],
        [0.5488, 0.2116, 0.5008]])

In [39]:
print(f"Shape of Tensor One", { tensor_one.shape })
print(f"Shape of Tensor Two", { tensor_two.shape })
print(f"Shape of Tensor Two Transposed", { tensor_two.T.shape})

Shape of Tensor One {torch.Size([3, 4])}
Shape of Tensor Two {torch.Size([3, 4])}
Shape of Tensor Two Transposed {torch.Size([4, 3])}


In [40]:
# Check matrix multiplication animation here: http://matrixmultiplication.xyz/

In [42]:
# matrix aggrgation  (min, max, average/mean )

tensor_aggr = torch.arange(1,101)
tensor_aggr

tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100])

In [43]:
tensor_aggr, tensor_aggr.dtype

(tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
          15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
          29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
          43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
          57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
          71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
          85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
          99, 100]),
 torch.int64)

In [44]:
#min
torch.min(tensor_aggr) , tensor_aggr.min() # 2 ways to do it

(tensor(1), tensor(1))

In [46]:
#max
torch.max(tensor_aggr) , tensor_aggr.max()

(tensor(100), tensor(100))

In [48]:
#mean
#try to run following - will fail because .mean() requires a tensor of float32 datatype
# torch.mean(tensor_aggr) # RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [50]:
torch.mean(tensor_aggr.type(torch.float32)) , tensor_aggr.type(torch.float32).mean()

(tensor(50.5000), tensor(50.5000))

In [59]:
#find index of min and max values

print(tensor_aggr.argmin())
print(tensor_aggr.argmin().item())
print(tensor_aggr.argmax())
print(tensor_aggr.argmax().item())

# we use this to implement softmax and softmin functions internally in neural networks

tensor(0)
0
tensor(99)
99


In [62]:
## 1/ Reshaping tensors: reshapes input tensor into defined shape
## 2/ View tensors: returns a view of an input tensor of certain shape but the keep the same memory as the original shape
## 3/ Stacking tensors: combine multiple tensor on top of each other (vstack) or side by side (hstack)
# https://pytorch.org/docs/stable/generated/torch.stack.html
# https://pytorch.org/docs/stable/generated/torch.vstack.html
# https://pytorch.org/docs/stable/generated/torch.hstack.html
# 4/ Squeeze: removes all 1 dimensions from a tensor
# 5/ Unqueeze: add a 1 dimension to a tensor
# 6/ Permute: Returns a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
### Reshaping Tensors

In [63]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [65]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# this would fail because we are tyring to reshape a 9 element tensor to 18 element tensor
# x_reshaped = x.reshape(1,18) # RuntimeError: shape '[1, 18]' is invalid for input of size 9

In [69]:
# but this would work
x_reshaped = x.reshape(9,1) # essentially we are reshaping but still have the exact same 9 slots
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [71]:
# even this would work because 3 x 3 is 9. we have to have equal number of slots irrespective of shape
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [73]:
### Change the view (view shares the same pointer)

y = torch.arange(1,101, 2)
y

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [80]:
# z = y.view(1,9) # RuntimeError: shape '[1, 9]' is invalid for input of size 50

In [81]:
z = y.view(1,50)
z, z.shape

(tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
          37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
          73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]]),
 torch.Size([1, 50]))

In [82]:
# Now changing z will change y

# change first element of z
z[:,0] = 100 # will update in y as well
z, y

(tensor([[100,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,
           29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
           57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,
           85,  87,  89,  91,  93,  95,  97,  99]]),
 tensor([100,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,
          29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
          57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,  83,
          85,  87,  89,  91,  93,  95,  97,  99]))

In [85]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x,x])
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [88]:
x_stacked = torch.stack([x,x,x,x,x], dim=0) # same as vstack
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [89]:
x_stacked = torch.stack([x,x,x,x,x], dim=1) # same as hstack
x_stacked

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [93]:
# x_stacked = torch.stack([x,x,x,x,x], dim=2) ## x_stacked = torch.stack([x,x,x,x,x], dim=1)
# x_stacked

In [91]:
x_stacked = torch.stack([x,x,x,x,x], dim=-2)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [92]:
x_stacked = torch.stack([x,x,x,x,x], dim=-1)
x_stacked

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [95]:
x_stacked_vstacked = torch.vstack([x,x,x,x,x])
x_stacked_vstacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [96]:
x_stacked_vstacked = torch.hstack([x,x,x,x,x])
x_stacked_vstacked

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [98]:
# Squeeze: Removes all single dimensions from a target of a tensor

In [103]:
x_stacked, x_stacked.shape

(tensor([[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9.]]),
 torch.Size([9, 5]))

In [104]:
x_stacked.squeeze(), x_stacked.squeeze().shape

(tensor([[1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.],
         [5., 5., 5., 5., 5.],
         [6., 6., 6., 6., 6.],
         [7., 7., 7., 7., 7.],
         [8., 8., 8., 8., 8.],
         [9., 9., 9., 9., 9.]]),
 torch.Size([9, 5]))

In [112]:
# no differnce in above example because there are no single dimensions

# lets takea an example now

tensor_to_squeeze = torch.tensor([[2,1,3,6,8,4]])
tensor_to_squeeze, tensor_to_squeeze.shape

(tensor([[2, 1, 3, 6, 8, 4]]), torch.Size([1, 6]))

In [113]:
tensor_to_squeeze.squeeze(), tensor_to_squeeze.squeeze().shape

(tensor([2, 1, 3, 6, 8, 4]), torch.Size([6]))

In [114]:
#unsqueeze
tensor_to_unsqueeze = tensor_to_squeeze.squeeze()
tensor_to_unsqueeze, tensor_to_unsqueeze.shape

(tensor([2, 1, 3, 6, 8, 4]), torch.Size([6]))

In [117]:
tensor_to_unsqueeze.unsqueeze(dim=0), tensor_to_unsqueeze.unsqueeze(dim=0).shape

(tensor([[2, 1, 3, 6, 8, 4]]), torch.Size([1, 6]))

In [118]:
tensor_to_unsqueeze.unsqueeze(dim=1), tensor_to_unsqueeze.unsqueeze(dim=1).shape

(tensor([[2],
         [1],
         [3],
         [6],
         [8],
         [4]]),
 torch.Size([6, 1]))

In [122]:
# Permute : The torch.permute() method in PyTorch is used to rearrange the dimensions of a tensor.
# You provide a sequence of dimension indices, and the tensor's dimensions are rearranged accordingly.

# Permute is used with image tensors

In [129]:
tensor_to_permute =  torch.rand(size=(224,224,3)) # height, width, color channels rgb
tensor_to_permute

tensor([[[0.6124, 0.7701, 0.1657],
         [0.2164, 0.4369, 0.1922],
         [0.8589, 0.5853, 0.1230],
         ...,
         [0.8408, 0.3393, 0.4945],
         [0.6867, 0.7791, 0.8048],
         [0.7604, 0.9032, 0.3584]],

        [[0.0183, 0.0154, 0.5086],
         [0.0358, 0.4198, 0.7903],
         [0.3958, 0.4449, 0.5056],
         ...,
         [0.9073, 0.5030, 0.3097],
         [0.2378, 0.5107, 0.9635],
         [0.0546, 0.3457, 0.5607]],

        [[0.6099, 0.2527, 0.6672],
         [0.8617, 0.6232, 0.1981],
         [0.6766, 0.2134, 0.1655],
         ...,
         [0.8051, 0.2170, 0.4186],
         [0.1718, 0.4572, 0.2794],
         [0.6596, 0.0807, 0.3438]],

        ...,

        [[0.3828, 0.0736, 0.4676],
         [0.0956, 0.1956, 0.2038],
         [0.5272, 0.4608, 0.2146],
         ...,
         [0.0159, 0.8684, 0.6785],
         [0.4478, 0.2071, 0.7071],
         [0.3985, 0.3529, 0.7144]],

        [[0.0376, 0.2835, 0.0416],
         [0.9479, 0.2192, 0.3212],
         [0.

In [135]:
print(f"Shape Before Permute: ", {tensor_to_permute.shape})
tensor_to_permute.permute(2, 0, 1), # shifts axis 0->1 , 1->2 , 2->0
print(f"Shape After Permute: ", {tensor_to_permute.permute(2, 0, 1).shape}) # color channels rgb , height, width,

Shape Before Permute:  {torch.Size([224, 224, 3])}
Shape After Permute:  {torch.Size([3, 224, 224])}


In [136]:
# Indexing (Selecting) Data Retrieval in Tensors

In [140]:
index_tensor = torch.arange(1,10).reshape(1,3,3) # for 9 elements 1 x 3 x 3
index_tensor , index_tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [143]:
index_tensor[0], index_tensor[0][0], index_tensor[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [147]:
index_tensor[0][1], index_tensor[0][2]

(tensor([4, 5, 6]), tensor([7, 8, 9]))

In [149]:
index_tensor[0][1][1], index_tensor[0][1][2]

(tensor(5), tensor(6))

In [150]:
# Use ":" to get all of target dimensions
index_tensor[:,0]

tensor([[1, 2, 3]])

In [151]:
index_tensor[0,:]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [152]:
# get all value of 0 and 1st dimension but only index of 2nd dimension
index_tensor[:, :, 1]

tensor([[2, 5, 8]])

In [153]:
index_tensor[:, :, 2]

tensor([[3, 6, 9]])

In [154]:
index_tensor[:, 1, :]

tensor([[4, 5, 6]])

In [156]:
index_tensor[:, 2, :]

tensor([[7, 8, 9]])