<a href="https://colab.research.google.com/github/afirdousi/pytorch-basics/blob/main/003_torch_numpy_and_reproducibility.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello Pytorch World!")
print(torch.__version__)

Hello Pytorch World!
2.0.1+cu118


In [2]:
# Pytorch tensors and Numpy
# NumPy is a numerical computing library


In [13]:
# NumPy Data --to--> PyTorch tensor
array = np.arange(1.0,11.0)
array
# array.dtype

# automatically gets converted into a float64 because numpy's default data type is flaot64 | can use .from_numpy(array).type(torch.float32) to convert
tensor = torch.from_numpy(array)
tensor

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64)

In [15]:
# If we change the value of numpy array, will the tensor created of from_numpy will change?
array = array * 10
array, tensor

# meaning .from_numpy created a copy and deos not pass reference

(array([ 100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,  900.,
        1000.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [21]:
# PyTorch tensor --to--> NumPy Data
tensor = torch.ones(100)
numpy_tensor = tensor.numpy()

# automatically gets converted into a float32 because pytorch's default data type is flaot32 |
# we cannot .type(torch.float64) here because numpy does not have this conversion/casting method
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
      dtype=float32)

In [22]:
# If we change the value of pytorch tensor, will the numpy created of .numpy() will change?
tensor = tensor * 10
numpy_tensor, tensor

# meaning .numpy() created a copy and deos not pass reference

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       dtype=float32),
 tensor([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
         10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
         10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
         10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
         10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
         10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
         10., 10., 10., 10., 10., 10., 10., 10., 10., 

In [23]:
# Reproducibility in PyTorch: https://pytorch.org/docs/stable/notes/randomness.html
# Reproducibility = trying to take random out of random (useful for Neural Networks random seeds)

In [25]:
 # everytime we run this, pytorch gives us fresh random numbers but what if
 # we want to share the exact same random numbers if we want to share this notebook or code with someone?
torch.rand(5,5)

tensor([[0.9065, 0.4169, 0.1124, 0.3001, 0.6991],
        [0.1594, 0.6399, 0.1300, 0.8928, 0.3401],
        [0.8621, 0.2243, 0.0619, 0.6158, 0.2455],
        [0.3419, 0.5432, 0.1338, 0.0702, 0.1570],
        [0.6626, 0.6094, 0.3136, 0.2323, 0.9808]])

In [26]:
# Create two random tensors
random_tensor_one = torch.rand(5,5)

In [27]:
random_tensor_two = torch.rand(5,5)

In [28]:
random_tensor_one, random_tensor_two

(tensor([[0.3910, 0.6245, 0.6944, 0.9901, 0.0575],
         [0.3924, 0.7594, 0.4346, 0.3765, 0.4985],
         [0.6304, 0.5357, 0.9133, 0.3469, 0.1605],
         [0.6045, 0.4394, 0.7319, 0.8237, 0.4014],
         [0.1909, 0.0098, 0.1229, 0.1901, 0.5477]]),
 tensor([[0.2161, 0.6427, 0.4984, 0.9854, 0.4525],
         [0.1567, 0.9346, 0.7444, 0.2773, 0.8145],
         [0.4128, 0.4717, 0.4652, 0.8922, 0.3245],
         [0.4364, 0.1012, 0.9079, 0.3851, 0.9148],
         [0.6663, 0.9836, 0.5717, 0.7952, 0.3038]]))

In [32]:
random_tensor_one == random_tensor_two

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [33]:
# If we share this notebook with anyone, the generated random numbers will be different
# What if I want to share the exact same random numbers?
# We do this through the concept of a random seed

# Set the random seed
RANDOM_SEED = 42 # 42 is a common one...this would be specific random flavor
torch.manual_seed(RANDOM_SEED)


In [35]:
random_tensor_one = torch.rand(5,5)
random_tensor_two = torch.rand(5,5)

random_tensor_one, random_tensor_two # Still didn't work

(tensor([[0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890],
         [0.2814, 0.7886, 0.5895, 0.7539, 0.1952]]),
 tensor([[0.0050, 0.3068, 0.1165, 0.9103, 0.6440],
         [0.7071, 0.6581, 0.4913, 0.8913, 0.1447],
         [0.5315, 0.1587, 0.6542, 0.3278, 0.6532],
         [0.3958, 0.9147, 0.2036, 0.2018, 0.2018],
         [0.9497, 0.6666, 0.9811, 0.0874, 0.0041]]))

In [37]:
#If you want to use torch's manual seed, you will have to call manual_seed everytime before you call .rand()

torch.manual_seed(RANDOM_SEED)
random_tensor_one = torch.rand(5,5)
torch.manual_seed(RANDOM_SEED)
random_tensor_two = torch.rand(5,5)

random_tensor_one, random_tensor_two # Still didn't work

(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
         [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
         [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]]))

In [38]:
random_tensor_one == random_tensor_two

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [39]:
# Learn more at https://en.wikipedia.org/wiki/Random_seed
# There is also a rnadom seed in numpy, check this: https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html