<a href="https://colab.research.google.com/github/afirdousi/pytorch-basics/blob/main/004_tensor_on_gpus_and_device_agnostic_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello Pytorch World!")
print(torch.__version__)

Hello Pytorch World!
2.0.1+cu118


In [ ]:
# Running tensor and PyTorch objects on GPUs makes the computation faster due to parallelism
# Thanks to CUDA, Nvidia Hardware and Pytorch

In [ ]:
# Steps
# 1. Getting a GPU
# ---- Use Google Colab (Colab Pro or Pro+): Start here, good for quick learning and experimentation
# ---- Use your own GPU  ( https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/ )
# ---- Use cloud computing ( GCP, AWS, Azure)

# ---- Running GPU + CUDA on local machine takes a bit of setup, check pytorch documentation

In [ ]:
# For Colab
# Goto Runtime -> Change Runtime Type --> Select GPU (You can T4 for free on Colab Free: https://www.nvidia.com/en-us/data-center/tesla-t4/)
# Once done, run the following:
!nvidia-smi

Fri Aug 18 06:11:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Check if you have GPU access with PyTorch
torch.cuda.is_available() # CUDA is Nvidia's programming interface over GPU

True

In [ ]:
# Setup Device Agnostic Concept
# You might not always have access to GPU but you want to use GPU whenever available
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# How to count the number of GPUs
torch.cuda.device_count() # if you are running larger models and if you have multiple devices, you might want to run one model on each device

1

In [ ]:
# Learn more here: https://pytorch.org/docs/stable/notes/cuda.html
# Check best practices for running Cuda: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
%%time
# Putting tensors and models on GPU for faster computations
tensor = torch.tensor([10,20,30,40,50], device='cpu')
print(tensor, tensor.device)

tensor = torch.tensor([10,20,30,40,50])
print(tensor, tensor.device) # even by default, device = cpu

tensor([10, 20, 30, 40, 50]) cpu
tensor([10, 20, 30, 40, 50]) cpu
CPU times: user 1.93 ms, sys: 0 ns, total: 1.93 ms
Wall time: 1.94 ms


In [ ]:
%%time
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

CPU times: user 192 µs, sys: 24 µs, total: 216 µs
Wall time: 226 µs


tensor([10, 20, 30, 40, 50], device='cuda:0')

In [ ]:
# Moving tensors back to CPU
# Tensors on GPU can't be transformed to NumPy

# Run and recomment it
# tensor_on_gpu.numpy() # TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

# Numpy doesn't work with GPU

In [ ]:
# How to fix GPU tensor to NumPy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([10, 20, 30, 40, 50])

In [ ]:
tensor_on_gpu # this remains unchanged

tensor([10, 20, 30, 40, 50], device='cuda:0')

In [ ]:
# Action: Learn how to run Pytorch to use multiple GPUs
# https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html

# For practicing fundamentals of PyTorch: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises